# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b1be4aab7a3149f285b9228e9fbc818f"
name = "Shop Producitfy Prod"
handle = "shop-producitfy-prod"
application_url = "https://shopify-app.rajatweb.dev/"
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "hydrogen-web.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://shopify-app.rajatweb.dev/auth/callback",
  "https://shopify-app.rajatweb.dev/auth/shopify/callback",
  "https://shopify-app.rajatweb.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
